apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.mainDocs.service.svcName}}
spec:
  type: {{ .Values.svcType}}
  ports:
    - targetPort: {{ .Values.containerPort}}
      port: {{ .Values.svcPort}}
      protocol: TCP
  selector:
    component: {{ .Values.mainDocs.deployment.labels}}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.adminDocs.service.svcName}}
spec:
  type: {{ .Values.svcType}}
  ports:
    - targetPort: {{ .Values.containerPort}}
      port: {{ .Values.svcPort}}
      protocol: TCP
  selector:
    component: {{ .Values.adminDocs.deployment.labels}}

