apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    component: node
  name: node-pvc
  namespace: pw-dev
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: gp2
  volumeMode: Filesystem
  
