apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.main.service.svcName}}
spec:
  type: {{ .Values.svcType}}
  ports:
    - targetPort: {{ .Values.containerPort}}
      port: {{ .Values.svcPort}}
      protocol: TCP
  selector:
    component: {{ .Values.main.deployment.labels}}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.admin.service.svcName}}
spec:
  type: {{ .Values.svcType}}
  ports:
    - targetPort: {{ .Values.containerPort}}
      port: {{ .Values.svcPort}}
      protocol: TCP
  selector:
    component: {{ .Values.admin.deployment.labels}}